# This workflow will build a package using Gradle
# and then verify and sing the plugin
# TODO publish the plugin to IntelliJ marketplace

name: Publish package to Maven Central

on:
  push:
    tags:
      - plugin_*

defaults:
  run:
    working-directory: ./intellij-plugin

jobs:
  build:
    name: Release
    runs-on: ubuntu-latest

    steps:
      - id: Publish
        uses: ./github/actions/plugin-publish-steps
          with:
            channel: "default"
