name: plugin-manual.yml
on:
  workflow_dispatch:
    inputs:
      channel:
        description: 'The channel to publish the plugin to'
        required: true
        default: 'dev'
        type: choice
        options:
          - dev
          - alpha
          - beta
jobs:
  build:
    name: Release
    runs-on: ubuntu-latest

    steps:
      - name: Fetch Sources
        uses: actions/checkout@v4

      - id: Publish
        uses: ./.github/actions/plugin-publish-steps
        with:
          channel: ${{ inputs.channel }}
