# This workflow will build a package using Gradle
# and then verify and sing the plugin

name: Publish package to Maven Central

on: push

defaults:
  run:
    working-directory: ./intellij-plugin

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Fetch Sources
        uses: actions/checkout@v4

      - id: build
        uses: ./.github/actions/plugin-build-steps
