# This workflow will build a package using Gradle
# and then verify and sing the plugin
# TODO publish the plugin to IntelliJ marketplace

name: Publish package to Maven Central

on:
  push:
    tags:
      - plugin_*

jobs:
  build:
    name: Release
    runs-on: ubuntu-latest

    steps:
      - name: Fetch Sources
        uses: actions/checkout@v4

      - id: Publish
        uses: ./.github/actions/plugin-publish-steps
        with:
          channel: "default"

      - name: Finished
        run: |
          echo "Plugin published to channel: ${{ inputs.channel }}"
        shell: bash