# This workflow will build a package using Gradle
# and then verify and sing the plugin
# TODO publish the plugin to IntelliJ marketplace

name: Publish package to Maven Central

on:
  push:
    tags:
      - plugin_*

defaults:
  run:
    working-directory: ./intellij-plugin

jobs:
  build:
    name: Release
    runs-on: ubuntu-latest

    strategy:
      matrix:
        ijp_branch: [242, 243]
        include:
          - ijp_version: 2024.2.5
            ijp_branch: 242
          - ijp_version: 2024.3.2
            ijp_branch: 243

    steps:
      - uses: prepare@v1

      - name: Build plugin
        env:
          IJP_VERSION: ${{ matrix.ijp_version }}
          IJP_BRANCH: ${{ matrix.ijp_branch }}
        run: ./gradlew buildPlugin

      - name: Run Plugin Verification tasks
        env:
          IJP_VERSION: ${{ matrix.ijp_version }}
          IJP_BRANCH: ${{ matrix.ijp_branch }}
        run: ./gradlew verifyPlugin

      - name: Sign Plugin
        env:
          IJP_VERSION: ${{ matrix.ijp_version }}
          IJP_BRANCH: ${{ matrix.ijp_branch }}
          PLUGIN_CERTIFICATE_CHAIN: ${{ secrets.PLUGIN_CERTIFICATE_CHAIN }}
          PLUGIN_PRIVATE_KEY: ${{ secrets.PLUGIN_PRIVATE_KEY }}
          PLUGIN_PRIVATE_KEY_PASSWORD: ${{ secrets.PLUGIN_PRIVATE_KEY_PASSWORD }}
        run: ./gradlew signPlugin

      - name: Release to plugin market
        env:
          IJP_VERSION: ${{ matrix.ijp_version }}
          IJP_BRANCH: ${{ matrix.ijp_branch }}
          PLUGIN_PUBLISH_TOKEN: ${{ secrets.PLUGIN_PUBLISH_TOKEN }}
        run: ./gradlew publishPlugin
